#ifdef IDIFF_HAVE_FFMPEG

#include <catch2/catch_test_macros.hpp>

#include "core/video_decoder.h"
#include "core/video_file_source.h"
#include "core/image_impl.h"

#include <string>

using namespace idiff;

// Path to a 48x64 video with SAR 4:3 (display 64x64), generated by CMake.
static const std::string kSarVideoPath = IDIFF_TEST_SAR_VIDEO_PATH;

static bool has_sar_video() { return !kSarVideoPath.empty(); }

// =============================================================================
// VideoDecoder::sar
// =============================================================================

TEST_CASE("VideoDecoder: sar() returns non-trivial SAR for anamorphic video",
          "[video][sar]") {
    if (!has_sar_video()) SKIP("SAR test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kSarVideoPath));

    auto sar = decoder.sar();
    // The test video is generated with -aspect 4:3 on a 48x64 source,
    // so SAR should be 4:3 (num=4, den=3).
    CHECK(sar.num > 0);
    CHECK(sar.den > 0);
    CHECK((sar.num != 1 || sar.den != 1));
}

TEST_CASE("VideoDecoder: sar() returns 1:1 for square-pixel video",
          "[video][sar]") {
    static const std::string kTestVideoPath = IDIFF_TEST_VIDEO_PATH;
    if (kTestVideoPath.empty()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    auto sar = decoder.sar();
    // The standard test video (64x64 testsrc) has SAR 1:1 or unset.
    // Either way, display_width == width.
    if (sar.num > 0 && sar.den > 0) {
        CHECK(sar.num == 1);
        CHECK(sar.den == 1);
    }
    // Unset SAR (0/0) is also acceptable for square-pixel content.
}

// =============================================================================
// VideoFileSource: SAR propagation to ImageInfo
// =============================================================================

TEST_CASE("VideoFileSource: read_frame propagates SAR to ImageInfo",
          "[video][sar]") {
    if (!has_sar_video()) SKIP("SAR test video not available");

    VideoFileSource source(kSarVideoPath);
    REQUIRE(source.is_valid());

    auto img = source.read_frame(0);
    REQUIRE(img != nullptr);

    const auto& info = img->info();
    // Coded pixel dimensions remain at the stored resolution.
    CHECK(info.width > 0);
    CHECK(info.height > 0);

    // SAR must be propagated.
    CHECK(info.sar_num > 0);
    CHECK(info.sar_den > 0);

    // display_width must differ from coded width when SAR != 1:1.
    CHECK(info.display_width() != info.width);
    CHECK(info.display_height() == info.height);
}

TEST_CASE("VideoFileSource: SAR makes display_width > coded width for wide SAR",
          "[video][sar]") {
    if (!has_sar_video()) SKIP("SAR test video not available");

    VideoFileSource source(kSarVideoPath);
    REQUIRE(source.is_valid());

    auto img = source.read_frame(0);
    REQUIRE(img != nullptr);

    const auto& info = img->info();
    // SAR 4:3 on 48x64: display = 48*4/3 x 64 = 64x64
    CHECK(info.display_width() > info.width);
    CHECK(info.display_height() == info.height);
}

TEST_CASE("VideoFileSource: format_description includes SAR for anamorphic video",
          "[video][sar]") {
    if (!has_sar_video()) SKIP("SAR test video not available");

    VideoFileSource source(kSarVideoPath);
    REQUIRE(source.is_valid());

    const std::string& fmt = source.format_description();
    INFO("format_description = " << fmt);
    CHECK(fmt.find("SAR") != std::string::npos);
}

TEST_CASE("VideoFileSource: read_keyframe propagates SAR to ImageInfo",
          "[video][sar]") {
    if (!has_sar_video()) SKIP("SAR test video not available");

    VideoFileSource source(kSarVideoPath);
    REQUIRE(source.is_valid());

    auto img = source.read_keyframe(0);
    REQUIRE(img != nullptr);

    const auto& info = img->info();
    CHECK(info.sar_num > 0);
    CHECK(info.sar_den > 0);
    CHECK(info.display_width() != info.width);
}

#endif  // IDIFF_HAVE_FFMPEG
