#ifdef IDIFF_HAVE_FFMPEG

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>

#include "core/video_decoder.h"
#include "core/video_file_source.h"

#include <cstring>
#include <string>

using namespace idiff;

// Path to the test video generated by CMake (10 frames, 64x64, solid red).
// If empty, the ffmpeg CLI was not found at configure time and tests are skipped.
static const std::string kTestVideoPath = IDIFF_TEST_VIDEO_PATH;

static bool has_test_video() {
    return !kTestVideoPath.empty();
}

// ============================================================================
// VideoDecoder tests
// ============================================================================

TEST_CASE("VideoDecoder: open valid file", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));
    REQUIRE(decoder.is_open());

    CHECK(decoder.width() == 64);
    CHECK(decoder.height() == 64);
    CHECK(decoder.frame_count() == 10);
    CHECK(decoder.fps() > 0.0);
    CHECK(decoder.bit_depth() == 8);
    CHECK_FALSE(decoder.codec_name().empty());
}

TEST_CASE("VideoDecoder: open invalid file path", "[video][decoder]") {
    VideoDecoder decoder;
    REQUIRE_FALSE(decoder.open("/nonexistent/path/to/video.mp4"));
    REQUIRE_FALSE(decoder.is_open());
    CHECK_FALSE(decoder.last_error().empty());
}

TEST_CASE("VideoDecoder: decode first frame", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    cv::Mat frame = decoder.decode_frame(0);
    REQUIRE_FALSE(frame.empty());
    CHECK(frame.cols == 64);
    CHECK(frame.rows == 64);
    CHECK(frame.channels() == 3);
    CHECK(frame.type() == CV_8UC3);
    CHECK(decoder.current_frame_index() == 0);
}

TEST_CASE("VideoDecoder: sequential decode", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    // Decode all 10 frames sequentially
    for (int i = 0; i < 10; ++i) {
        cv::Mat frame = decoder.decode_frame(i);
        REQUIRE_FALSE(frame.empty());
        CHECK(frame.cols == 64);
        CHECK(frame.rows == 64);
        CHECK(decoder.current_frame_index() == i);
    }
}

TEST_CASE("VideoDecoder: cache hit returns same data", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    cv::Mat frame1 = decoder.decode_frame(3);
    REQUIRE_FALSE(frame1.empty());

    // Second call to same index should return cached (identical) data
    cv::Mat frame2 = decoder.decode_frame(3);
    REQUIRE_FALSE(frame2.empty());

    // Pixel data should be identical
    CHECK(std::memcmp(frame1.data, frame2.data,
                      static_cast<size_t>(frame1.total() * frame1.elemSize())) == 0);
}

TEST_CASE("VideoDecoder: seek to arbitrary frame", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    // Decode frame 7 directly (requires seek)
    cv::Mat frame = decoder.decode_frame(7);
    REQUIRE_FALSE(frame.empty());
    CHECK(frame.cols == 64);
    CHECK(frame.rows == 64);
    CHECK(decoder.current_frame_index() == 7);
}

TEST_CASE("VideoDecoder: seek consistency with sequential decode", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    // Decode frame 5 sequentially
    VideoDecoder decoder_seq;
    REQUIRE(decoder_seq.open(kTestVideoPath));
    cv::Mat seq_frame;
    for (int i = 0; i <= 5; ++i) {
        seq_frame = decoder_seq.decode_frame(i);
    }
    REQUIRE_FALSE(seq_frame.empty());

    // Decode frame 5 via seek (from a fresh decoder)
    VideoDecoder decoder_seek;
    REQUIRE(decoder_seek.open(kTestVideoPath));
    cv::Mat seek_frame = decoder_seek.decode_frame(5);
    REQUIRE_FALSE(seek_frame.empty());

    // Both should produce identical pixel data
    REQUIRE(seq_frame.size() == seek_frame.size());
    CHECK(std::memcmp(seq_frame.data, seek_frame.data,
                      static_cast<size_t>(seq_frame.total() * seq_frame.elemSize())) == 0);
}

TEST_CASE("VideoDecoder: out-of-range frame index", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    cv::Mat frame = decoder.decode_frame(-1);
    CHECK(frame.empty());

    frame = decoder.decode_frame(10);  // exactly at count (0-based, so invalid)
    CHECK(frame.empty());

    frame = decoder.decode_frame(100);
    CHECK(frame.empty());
}

TEST_CASE("VideoDecoder: close and reopen", "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));
    decoder.close();
    CHECK_FALSE(decoder.is_open());

    // Reopen should work
    REQUIRE(decoder.open(kTestVideoPath));
    CHECK(decoder.is_open());
    CHECK(decoder.frame_count() == 10);
}

// ============================================================================
// VideoFileSource tests
// ============================================================================

TEST_CASE("VideoFileSource: open and read frame", "[video][source]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoFileSource source(kTestVideoPath);
    REQUIRE(source.is_valid());

    CHECK(source.frame_count() == 10);
    CHECK(source.width() == 64);
    CHECK(source.height() == 64);
    CHECK_FALSE(source.format_description().empty());

    auto img = source.read_frame(0);
    REQUIRE(img != nullptr);
    CHECK(img->info().width == 64);
    CHECK(img->info().height == 64);
    CHECK(img->info().pixel_format == PixelFormat::RGB8);
}

TEST_CASE("VideoFileSource: out-of-range returns nullptr", "[video][source]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoFileSource source(kTestVideoPath);
    REQUIRE(source.is_valid());

    auto img = source.read_frame(-1);
    CHECK(img == nullptr);
    CHECK_FALSE(source.last_error().empty());

    img = source.read_frame(10);
    CHECK(img == nullptr);
}

TEST_CASE("VideoFileSource: invalid path", "[video][source]") {
    VideoFileSource source("/nonexistent/video.mp4");
    CHECK_FALSE(source.is_valid());
    CHECK(source.frame_count() == 0);
    CHECK_FALSE(source.last_error().empty());
}

TEST_CASE("VideoFileSource: consecutive frames differ", "[video][source]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoFileSource source(kTestVideoPath);
    REQUIRE(source.is_valid());
    REQUIRE(source.frame_count() >= 2);

    auto img0 = source.read_frame(0);
    auto img1 = source.read_frame(1);
    REQUIRE(img0 != nullptr);
    REQUIRE(img1 != nullptr);

    // For a constant-color video, frames may be identical.
    // But the test verifies that read_frame returns successfully for
    // consecutive indices (the decode pipeline works).
    CHECK(img0->info().width == img1->info().width);
    CHECK(img0->info().height == img1->info().height);
}

// ============================================================================
// is_video_file_extension tests
// ============================================================================

TEST_CASE("is_video_file_extension: recognized extensions", "[video][util]") {
    CHECK(is_video_file_extension("video.mp4"));
    CHECK(is_video_file_extension("video.MP4"));
    CHECK(is_video_file_extension("/path/to/file.mkv"));
    CHECK(is_video_file_extension("clip.mov"));
    CHECK(is_video_file_extension("stream.avi"));
    CHECK(is_video_file_extension("web.webm"));
    CHECK(is_video_file_extension("broadcast.ts"));
    CHECK(is_video_file_extension("mobile.m4v"));
}

TEST_CASE("is_video_file_extension: non-video extensions", "[video][util]") {
    CHECK_FALSE(is_video_file_extension("image.png"));
    CHECK_FALSE(is_video_file_extension("photo.jpg"));
    CHECK_FALSE(is_video_file_extension("data.json"));
    CHECK_FALSE(is_video_file_extension("raw.yuv"));
    CHECK_FALSE(is_video_file_extension("noextension"));
}

// ============================================================================
// Rotation tests
// ============================================================================

TEST_CASE("VideoDecoder: default autorotate is enabled", "[video][rotation]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    CHECK(decoder.autorotate() == true);
    CHECK_FALSE(decoder.has_manual_rotation());
    // Test video has no rotation metadata, so detected should be None
    CHECK(decoder.detected_rotation() == VideoRotation::None);
    CHECK(decoder.effective_rotation() == VideoRotation::None);
}

TEST_CASE("VideoDecoder: manual rotation changes dimensions", "[video][rotation]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    // Original: 64x64 (square, so dimensions won't change, but API should work)
    CHECK(decoder.coded_width() == 64);
    CHECK(decoder.coded_height() == 64);
    CHECK(decoder.width() == 64);
    CHECK(decoder.height() == 64);

    // Set 90° rotation — for a square video, dimensions stay the same
    decoder.set_manual_rotation(VideoRotation::CW90);
    CHECK(decoder.has_manual_rotation());
    CHECK(decoder.effective_rotation() == VideoRotation::CW90);
    // For square video: width and height are swapped but equal
    CHECK(decoder.width() == 64);
    CHECK(decoder.height() == 64);
}

TEST_CASE("VideoDecoder: manual rotation applies to decoded frame", "[video][rotation]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    // Decode without rotation
    decoder.set_autorotate(false);
    cv::Mat no_rot = decoder.decode_frame(0);
    REQUIRE_FALSE(no_rot.empty());

    // Decode with 180° rotation
    decoder.set_manual_rotation(VideoRotation::CW180);
    cv::Mat rot180 = decoder.decode_frame(0);
    REQUIRE_FALSE(rot180.empty());

    // Dimensions should be the same for 180°
    CHECK(rot180.cols == no_rot.cols);
    CHECK(rot180.rows == no_rot.rows);

    // The pixel data should differ (rotated 180°)
    // For a solid-color frame they might be identical, but the API should work
    CHECK(rot180.type() == CV_8UC3);
}

TEST_CASE("VideoDecoder: clear manual rotation reverts to auto", "[video][rotation]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    decoder.set_manual_rotation(VideoRotation::CW90);
    CHECK(decoder.has_manual_rotation());
    CHECK(decoder.effective_rotation() == VideoRotation::CW90);

    decoder.clear_manual_rotation();
    CHECK_FALSE(decoder.has_manual_rotation());
    // Should revert to detected (None for test video)
    CHECK(decoder.effective_rotation() == VideoRotation::None);
}

TEST_CASE("VideoDecoder: disable autorotate", "[video][rotation]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    decoder.set_autorotate(false);
    CHECK(decoder.autorotate() == false);
    CHECK(decoder.effective_rotation() == VideoRotation::None);
}

#endif // IDIFF_HAVE_FFMPEG
