#ifdef IDIFF_HAVE_FFMPEG

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>

#include "core/video_decoder.h"
#include "core/video_file_source.h"

#include <cstring>
#include <string>

using namespace idiff;

// Path to the test video generated by CMake (10 frames, 64x64, solid red).
// If empty, the ffmpeg CLI was not found at configure time and tests are
// skipped.
static const std::string kTestVideoPath = IDIFF_TEST_VIDEO_PATH;

static bool has_test_video() { return !kTestVideoPath.empty(); }

// =============================================================================
// VideoDecoder: lifecycle, metadata and default rotation state.
// =============================================================================

TEST_CASE("VideoDecoder: open, query metadata, close and reopen",
          "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));
    REQUIRE(decoder.is_open());

    SECTION("metadata reflects the encoded video") {
        CHECK(decoder.width() == 64);
        CHECK(decoder.height() == 64);
        CHECK(decoder.frame_count() == 10);
        CHECK(decoder.fps() > 0.0);
        CHECK(decoder.bit_depth() == 8);
        CHECK_FALSE(decoder.codec_name().empty());
    }

    SECTION("default rotation state has autorotate on with no manual override") {
        CHECK(decoder.autorotate() == true);
        CHECK_FALSE(decoder.has_manual_rotation());
        CHECK(decoder.detected_rotation() == VideoRotation::None);
        CHECK(decoder.effective_rotation() == VideoRotation::None);
    }

    SECTION("close then reopen leaves the decoder usable") {
        decoder.close();
        CHECK_FALSE(decoder.is_open());
        REQUIRE(decoder.open(kTestVideoPath));
        CHECK(decoder.is_open());
        CHECK(decoder.frame_count() == 10);
    }
}

// =============================================================================
// VideoDecoder: decoding, seeking and caching.
// =============================================================================

TEST_CASE("VideoDecoder: decodes frames and stays seek/cache consistent",
          "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    SECTION("sequential decode walks all frames") {
        for (int i = 0; i < 10; ++i) {
            cv::Mat f = decoder.decode_frame(i);
            REQUIRE_FALSE(f.empty());
            CHECK(f.cols == 64);
            CHECK(f.rows == 64);
            CHECK(f.channels() == 3);
            CHECK(f.type() == CV_8UC3);
            CHECK(decoder.current_frame_index() == i);
        }
    }

    SECTION("seek-then-decode produces the same bytes as sequential decode") {
        VideoDecoder decoder_seq;
        REQUIRE(decoder_seq.open(kTestVideoPath));
        cv::Mat seq_frame;
        for (int i = 0; i <= 5; ++i) {
            seq_frame = decoder_seq.decode_frame(i);
        }
        REQUIRE_FALSE(seq_frame.empty());

        VideoDecoder decoder_seek;
        REQUIRE(decoder_seek.open(kTestVideoPath));
        cv::Mat seek_frame = decoder_seek.decode_frame(5);
        REQUIRE_FALSE(seek_frame.empty());
        REQUIRE(seq_frame.size() == seek_frame.size());
        CHECK(std::memcmp(seq_frame.data, seek_frame.data,
                          static_cast<size_t>(seq_frame.total() *
                                              seq_frame.elemSize())) == 0);
    }

    SECTION("cache returns identical pixel data on repeated index") {
        cv::Mat first = decoder.decode_frame(3);
        REQUIRE_FALSE(first.empty());
        cv::Mat second = decoder.decode_frame(3);
        REQUIRE_FALSE(second.empty());
        CHECK(std::memcmp(first.data, second.data,
                          static_cast<size_t>(first.total() *
                                              first.elemSize())) == 0);
    }
}

// =============================================================================
// VideoDecoder: rotation behavior.
// =============================================================================

TEST_CASE("VideoDecoder: rotation overrides apply, revert and disable cleanly",
          "[video][decoder][rotation]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    SECTION("manual rotation applies to dimensions and decoded frame") {
        // Without rotation.
        decoder.set_autorotate(false);
        cv::Mat no_rot = decoder.decode_frame(0);
        REQUIRE_FALSE(no_rot.empty());
        CHECK(decoder.coded_width() == 64);
        CHECK(decoder.coded_height() == 64);

        // 90° on a square video: width/height swap but equal.
        decoder.set_manual_rotation(VideoRotation::CW90);
        CHECK(decoder.has_manual_rotation());
        CHECK(decoder.effective_rotation() == VideoRotation::CW90);
        CHECK(decoder.width() == 64);
        CHECK(decoder.height() == 64);

        // 180° decodes a frame of the same dimensions.
        decoder.set_manual_rotation(VideoRotation::CW180);
        cv::Mat rot180 = decoder.decode_frame(0);
        REQUIRE_FALSE(rot180.empty());
        CHECK(rot180.cols == no_rot.cols);
        CHECK(rot180.rows == no_rot.rows);
        CHECK(rot180.type() == CV_8UC3);
    }

    SECTION("clear_manual_rotation reverts to detected") {
        decoder.set_manual_rotation(VideoRotation::CW90);
        CHECK(decoder.has_manual_rotation());
        CHECK(decoder.effective_rotation() == VideoRotation::CW90);
        decoder.clear_manual_rotation();
        CHECK_FALSE(decoder.has_manual_rotation());
        CHECK(decoder.effective_rotation() == VideoRotation::None);
    }

    SECTION("disabling autorotate yields VideoRotation::None") {
        decoder.set_autorotate(false);
        CHECK(decoder.autorotate() == false);
        CHECK(decoder.effective_rotation() == VideoRotation::None);
    }
}

// =============================================================================
// VideoDecoder: error paths.
// =============================================================================

TEST_CASE("VideoDecoder: rejects bad open and out-of-range frame indices",
          "[video][decoder]") {
    SECTION("nonexistent file fails open and last_error is set") {
        VideoDecoder decoder;
        REQUIRE_FALSE(decoder.open("/nonexistent/path/to/video.mp4"));
        REQUIRE_FALSE(decoder.is_open());
        CHECK_FALSE(decoder.last_error().empty());
    }

    SECTION("out-of-range frame indices return empty") {
        if (!has_test_video()) SKIP("Test video not available");
        VideoDecoder decoder;
        REQUIRE(decoder.open(kTestVideoPath));
        CHECK(decoder.decode_frame(-1).empty());
        CHECK(decoder.decode_frame(10).empty());  // exactly at count
        CHECK(decoder.decode_frame(100).empty());
    }
}

// =============================================================================
// VideoFileSource.
// =============================================================================

TEST_CASE("VideoFileSource: opens, exposes metadata, reads consecutive frames",
          "[video][source]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoFileSource source(kTestVideoPath);
    REQUIRE(source.is_valid());

    CHECK(source.frame_count() == 10);
    CHECK(source.width() == 64);
    CHECK(source.height() == 64);
    CHECK_FALSE(source.format_description().empty());

    auto img0 = source.read_frame(0);
    auto img1 = source.read_frame(1);
    REQUIRE(img0 != nullptr);
    REQUIRE(img1 != nullptr);
    CHECK(img0->info().width == 64);
    CHECK(img0->info().height == 64);
    CHECK(img0->info().pixel_format == PixelFormat::RGB8);
    // Constant-color video frames may be identical bytewise; we just
    // verify the decode pipeline returns a frame for each index.
    CHECK(img0->info().width == img1->info().width);
    CHECK(img0->info().height == img1->info().height);
}

TEST_CASE("VideoFileSource: rejects bad path and bad frame indices",
          "[video][source]") {
    SECTION("nonexistent path") {
        VideoFileSource source("/nonexistent/video.mp4");
        CHECK_FALSE(source.is_valid());
        CHECK(source.frame_count() == 0);
        CHECK_FALSE(source.last_error().empty());
    }
    SECTION("out-of-range read_frame returns nullptr") {
        if (!has_test_video()) SKIP("Test video not available");
        VideoFileSource source(kTestVideoPath);
        REQUIRE(source.is_valid());
        CHECK(source.read_frame(-1) == nullptr);
        CHECK_FALSE(source.last_error().empty());
        CHECK(source.read_frame(10) == nullptr);
    }
}

// =============================================================================
// is_video_file_extension.
// =============================================================================

TEST_CASE("is_video_file_extension: distinguishes video from non-video paths",
          "[video][util]") {
    SECTION("recognized video extensions") {
        CHECK(is_video_file_extension("video.mp4"));
        CHECK(is_video_file_extension("video.MP4"));
        CHECK(is_video_file_extension("/path/to/file.mkv"));
        CHECK(is_video_file_extension("clip.mov"));
        CHECK(is_video_file_extension("stream.avi"));
        CHECK(is_video_file_extension("web.webm"));
        CHECK(is_video_file_extension("broadcast.ts"));
        CHECK(is_video_file_extension("mobile.m4v"));
    }
    SECTION("non-video extensions") {
        CHECK_FALSE(is_video_file_extension("image.png"));
        CHECK_FALSE(is_video_file_extension("photo.jpg"));
        CHECK_FALSE(is_video_file_extension("data.json"));
        CHECK_FALSE(is_video_file_extension("raw.yuv"));
        CHECK_FALSE(is_video_file_extension("noextension"));
    }
}

#endif  // IDIFF_HAVE_FFMPEG
