#ifdef IDIFF_HAVE_FFMPEG

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>

#include "core/video_decoder.h"
#include "core/video_file_source.h"
#include "core/image_impl.h"

#include <cstring>
#include <string>

using namespace idiff;

// Path to the test video generated by CMake.  Encoded with libx264:
//   10 frames at 64x64, lavfi `testsrc` (moving colour bars + frame
//   counter, so every frame is visually distinct), GOP=1 (every
//   frame is a keyframe).  If empty, the ffmpeg CLI was not found at
//   configure time and tests are skipped.
static const std::string kTestVideoPath = IDIFF_TEST_VIDEO_PATH;

static bool has_test_video() { return !kTestVideoPath.empty(); }

// =============================================================================
// VideoDecoder: lifecycle, metadata and default rotation state.
// =============================================================================

TEST_CASE("VideoDecoder: open, query metadata, close and reopen",
          "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));
    REQUIRE(decoder.is_open());

    SECTION("metadata reflects the encoded video") {
        CHECK(decoder.width() == 64);
        CHECK(decoder.height() == 64);
        CHECK(decoder.frame_count() == 10);
        CHECK(decoder.fps() > 0.0);
        CHECK(decoder.bit_depth() == 8);
        CHECK_FALSE(decoder.codec_name().empty());
    }

    SECTION("default rotation state has autorotate on with no manual override") {
        CHECK(decoder.autorotate() == true);
        CHECK_FALSE(decoder.has_manual_rotation());
        CHECK(decoder.detected_rotation() == VideoRotation::None);
        CHECK(decoder.effective_rotation() == VideoRotation::None);
    }

    SECTION("close then reopen leaves the decoder usable") {
        decoder.close();
        CHECK_FALSE(decoder.is_open());
        REQUIRE(decoder.open(kTestVideoPath));
        CHECK(decoder.is_open());
        CHECK(decoder.frame_count() == 10);
    }
}

// =============================================================================
// VideoDecoder: decoding, seeking and caching.
// =============================================================================

TEST_CASE("VideoDecoder: decodes frames and stays seek/cache consistent",
          "[video][decoder]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    SECTION("sequential decode walks all frames") {
        for (int i = 0; i < 10; ++i) {
            cv::Mat f = decoder.decode_frame(i);
            REQUIRE_FALSE(f.empty());
            CHECK(f.cols == 64);
            CHECK(f.rows == 64);
            CHECK(f.channels() == 3);
            CHECK(f.type() == CV_8UC3);
            CHECK(decoder.current_frame_index() == i);
        }
    }

    SECTION("seek-then-decode produces the same bytes as sequential decode") {
        VideoDecoder decoder_seq;
        REQUIRE(decoder_seq.open(kTestVideoPath));
        cv::Mat seq_frame;
        for (int i = 0; i <= 5; ++i) {
            seq_frame = decoder_seq.decode_frame(i);
        }
        REQUIRE_FALSE(seq_frame.empty());

        VideoDecoder decoder_seek;
        REQUIRE(decoder_seek.open(kTestVideoPath));
        cv::Mat seek_frame = decoder_seek.decode_frame(5);
        REQUIRE_FALSE(seek_frame.empty());
        REQUIRE(seq_frame.size() == seek_frame.size());
        CHECK(std::memcmp(seq_frame.data, seek_frame.data,
                          static_cast<size_t>(seq_frame.total() *
                                              seq_frame.elemSize())) == 0);
    }

    SECTION("cache returns identical pixel data on repeated index") {
        cv::Mat first = decoder.decode_frame(3);
        REQUIRE_FALSE(first.empty());
        cv::Mat second = decoder.decode_frame(3);
        REQUIRE_FALSE(second.empty());
        CHECK(std::memcmp(first.data, second.data,
                          static_cast<size_t>(first.total() *
                                              first.elemSize())) == 0);
    }
}

// =============================================================================
// VideoDecoder: rotation behavior.
// =============================================================================

TEST_CASE("VideoDecoder: rotation overrides apply, revert and disable cleanly",
          "[video][decoder][rotation]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoDecoder decoder;
    REQUIRE(decoder.open(kTestVideoPath));

    SECTION("manual rotation applies to dimensions and decoded frame") {
        // Without rotation.
        decoder.set_autorotate(false);
        cv::Mat no_rot = decoder.decode_frame(0);
        REQUIRE_FALSE(no_rot.empty());
        CHECK(decoder.coded_width() == 64);
        CHECK(decoder.coded_height() == 64);

        // 90° on a square video: width/height swap but equal.
        decoder.set_manual_rotation(VideoRotation::CW90);
        CHECK(decoder.has_manual_rotation());
        CHECK(decoder.effective_rotation() == VideoRotation::CW90);
        CHECK(decoder.width() == 64);
        CHECK(decoder.height() == 64);

        // 180° decodes a frame of the same dimensions.
        decoder.set_manual_rotation(VideoRotation::CW180);
        cv::Mat rot180 = decoder.decode_frame(0);
        REQUIRE_FALSE(rot180.empty());
        CHECK(rot180.cols == no_rot.cols);
        CHECK(rot180.rows == no_rot.rows);
        CHECK(rot180.type() == CV_8UC3);
    }

    SECTION("clear_manual_rotation reverts to detected") {
        decoder.set_manual_rotation(VideoRotation::CW90);
        CHECK(decoder.has_manual_rotation());
        CHECK(decoder.effective_rotation() == VideoRotation::CW90);
        decoder.clear_manual_rotation();
        CHECK_FALSE(decoder.has_manual_rotation());
        CHECK(decoder.effective_rotation() == VideoRotation::None);
    }

    SECTION("disabling autorotate yields VideoRotation::None") {
        decoder.set_autorotate(false);
        CHECK(decoder.autorotate() == false);
        CHECK(decoder.effective_rotation() == VideoRotation::None);
    }
}

// =============================================================================
// VideoDecoder: error paths.
// =============================================================================

TEST_CASE("VideoDecoder: rejects bad open and out-of-range frame indices",
          "[video][decoder]") {
    SECTION("nonexistent file fails open and last_error is set") {
        VideoDecoder decoder;
        REQUIRE_FALSE(decoder.open("/nonexistent/path/to/video.mp4"));
        REQUIRE_FALSE(decoder.is_open());
        CHECK_FALSE(decoder.last_error().empty());
    }

    SECTION("out-of-range frame indices return empty") {
        if (!has_test_video()) SKIP("Test video not available");
        VideoDecoder decoder;
        REQUIRE(decoder.open(kTestVideoPath));
        CHECK(decoder.decode_frame(-1).empty());
        CHECK(decoder.decode_frame(10).empty());  // exactly at count
        CHECK(decoder.decode_frame(100).empty());
    }
}

// =============================================================================
// VideoFileSource.
// =============================================================================

TEST_CASE("VideoFileSource: opens, exposes metadata, reads consecutive frames",
          "[video][source]") {
    if (!has_test_video()) SKIP("Test video not available");

    VideoFileSource source(kTestVideoPath);
    REQUIRE(source.is_valid());

    CHECK(source.frame_count() == 10);
    CHECK(source.width() == 64);
    CHECK(source.height() == 64);

    SECTION("format_description names the codec, dimensions and bit depth") {
        const std::string& fmt = source.format_description();
        INFO("format_description = " << fmt);
        REQUIRE_FALSE(fmt.empty());
        // Test video is encoded with libx264 and decoded as 8-bit
        // yuv420p; the description string follows the
        // "<codec> <W>x<H> <depth>-bit" layout.
        CHECK(fmt.find("h264")    != std::string::npos);
        CHECK(fmt.find("64x64")   != std::string::npos);
        CHECK(fmt.find("8-bit")   != std::string::npos);
    }

    SECTION("read_frame populates the Image with correct metadata") {
        auto img = source.read_frame(0);
        REQUIRE(img != nullptr);
        const auto& info = img->info();
        CHECK(info.width == 64);
        CHECK(info.height == 64);
        CHECK(info.pixel_format == PixelFormat::RGB8);
        CHECK(info.bit_depth == 8);
        CHECK(info.source_bit_depth == 8);
        CHECK_FALSE(info.has_alpha);
        CHECK_FALSE(info.color_space.empty());
    }

    SECTION("read_frame returns distinct pixels for distinct indices") {
        // The test source is `testsrc` (moving colour bars + frame
        // counter), so adjacent frames must differ at the pixel
        // level.  This pins down the contract that read_frame(n)
        // really decodes frame n -- a regression that returned the
        // same cached frame for every index would slip past the
        // metadata-only checks above.
        auto img0 = source.read_frame(0);
        auto img1 = source.read_frame(1);
        auto img9 = source.read_frame(9);
        REQUIRE(img0 != nullptr);
        REQUIRE(img1 != nullptr);
        REQUIRE(img9 != nullptr);

        const cv::Mat& m0 = img0->internal().mat;
        const cv::Mat& m1 = img1->internal().mat;
        const cv::Mat& m9 = img9->internal().mat;
        REQUIRE(m0.size() == m1.size());
        REQUIRE(m0.size() == m9.size());

        const size_t bytes =
            static_cast<size_t>(m0.total() * m0.elemSize());
        CHECK(std::memcmp(m0.data, m1.data, bytes) != 0);
        CHECK(std::memcmp(m0.data, m9.data, bytes) != 0);
        CHECK(std::memcmp(m1.data, m9.data, bytes) != 0);
    }

    SECTION("read_keyframe returns an image with matching metadata") {
        // The test video is encoded with GOP=1, so every frame is a
        // keyframe and read_keyframe(n) must succeed for any valid n.
        auto img = source.read_keyframe(3);
        REQUIRE(img != nullptr);
        const auto& info = img->info();
        CHECK(info.width == 64);
        CHECK(info.height == 64);
        CHECK(info.pixel_format == PixelFormat::RGB8);
        CHECK(info.bit_depth == 8);
        CHECK(info.source_bit_depth == 8);
    }
}

TEST_CASE("VideoFileSource: rejects bad path and bad frame indices",
          "[video][source]") {
    SECTION("nonexistent path") {
        VideoFileSource source("/nonexistent/video.mp4");
        CHECK_FALSE(source.is_valid());
        CHECK(source.frame_count() == 0);
        CHECK_FALSE(source.last_error().empty());
    }
    SECTION("out-of-range read_frame returns nullptr") {
        if (!has_test_video()) SKIP("Test video not available");
        VideoFileSource source(kTestVideoPath);
        REQUIRE(source.is_valid());
        CHECK(source.read_frame(-1) == nullptr);
        CHECK_FALSE(source.last_error().empty());
        CHECK(source.read_frame(10) == nullptr);
    }
    SECTION("out-of-range read_keyframe returns nullptr") {
        if (!has_test_video()) SKIP("Test video not available");
        VideoFileSource source(kTestVideoPath);
        REQUIRE(source.is_valid());
        CHECK(source.read_keyframe(-1) == nullptr);
        CHECK_FALSE(source.last_error().empty());
        CHECK(source.read_keyframe(10) == nullptr);
    }
}

// =============================================================================
// is_video_file_extension.
// =============================================================================

TEST_CASE("is_video_file_extension: distinguishes video from non-video paths",
          "[video][util]") {
    SECTION("recognized video extensions") {
        CHECK(is_video_file_extension("video.mp4"));
        CHECK(is_video_file_extension("video.MP4"));
        CHECK(is_video_file_extension("/path/to/file.mkv"));
        CHECK(is_video_file_extension("clip.mov"));
        CHECK(is_video_file_extension("stream.avi"));
        CHECK(is_video_file_extension("web.webm"));
        CHECK(is_video_file_extension("broadcast.ts"));
        CHECK(is_video_file_extension("mobile.m4v"));
    }
    SECTION("non-video extensions") {
        CHECK_FALSE(is_video_file_extension("image.png"));
        CHECK_FALSE(is_video_file_extension("photo.jpg"));
        CHECK_FALSE(is_video_file_extension("data.json"));
        CHECK_FALSE(is_video_file_extension("raw.yuv"));
        CHECK_FALSE(is_video_file_extension("noextension"));
    }
}

#endif  // IDIFF_HAVE_FFMPEG
